---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-full-stack-api
spec: 
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector: 
    matchLabels: 
      name: restaurant-full-stack-api
  template:
    metadata:
      labels:
        name: restaurant-full-stack-api
    spec:
      containers:
        - name: application
          image: "cmcki85/restaurant-full-stack:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env: 
            - name: DB_PORT
            value: "$DB_PORT"
            - name: DB_HOST
              value: "$DB_HOST"
            - name: DB_PASSWORD
              value: "$DB_PASSWORD"
            - name: DB_TABLE
              value: "$DB_TABLE"
            - name: DB_USERNAME
              value: "$DB_USERNAME"